---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /srv/plex/library:/config
      - /srv/plex/tvseries:/tv
      - /srv/plex/movies:/movies
    restart: unless-stopped
